name: Github Pages Deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-dir: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Upload assets artifact
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: assets

      - name: Build site artifact
        run: |
          docker compose up jekyll-build-prod

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ${{ needs.build.outputs.build-dir }}/
      - name: Download assets artifact
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: ${{ needs.build.outputs.build-dir }}/assets
      - name: Setup Github Pages
        uses: actions/configure-pages@v4
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ needs.build.outputs.build-dir }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
